CREATE DATABASE IF NOT EXISTS job;
CREATE DATABASE IF NOT EXISTS company;
CREATE DATABASE IF NOT EXISTS review;

GRANT ALL PRIVILEGES ON job.* TO 'vinod'@'%';
GRANT ALL PRIVILEGES ON company.* TO 'vinod'@'%';
GRANT ALL PRIVILEGES ON review.* TO 'vinod'@'%';
FLUSH PRIVILEGES;